[package]
name = "metrics-catalogue"
version = "0.1.0"
edition = "2018"

[workspace]
members = [ "macros" ]

[dependencies]
metrics-catalogue-macros = { path = "macros", version = "0.1" }
metrics = "0.16"
